WebApplication2/Models/University.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class University
    {
        public int UniversityId { get; set; }
        public string Name { get; set; } // название факультета
        public int Rating { get; set; } // успеваемость факультета 
        public ICollection<Professors> Proffesor{ get; set; }
        public ICollection<Directions> Direction { get; set; }
        public ICollection<Sections> Section { get; set; }
        public University()
        {
             Section= new List<Sections>();
        }

    }
}

WebApplication2/Controllers/UniversityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Managers.UniversityManager;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class UniversityController : Controller
    {
        private readonly IUniversityManager Manager;
        public UniversityController(IUniversityManager manager)
        {
            Manager = manager;
        }

        public async Task<IActionResult> University()
        {
            return View(await Manager.GetAll());
        }

       public async Task<IActionResult> SortByRating()
      {
           return View( Manager.SortByRating());
       }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(University university)
        {
            await Manager.Add(university);
            return RedirectToAction(nameof(University));
        }
        [HttpGet]
        public async Task<ActionResult> DeleteUniversity(int id)
        {
            await Manager.DeleteById(id);
            return RedirectToAction(nameof(University));
        }
        [HttpGet]
        public async Task<ViewResult> UpdateUniversity(int id)
        {
            return View(await Manager.GetById(id));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateUniversity(int id, University university)
        {
            await Manager.UpdateById(id, university);
            return RedirectToAction(nameof(university));
        }
    }
}

WebApplication2/Views/University/Create.cshtml
@model WebApplication2.Models.University
@{
    ViewBag.Title = "Добавление пользователи";
}
<style>
    .control-label {
        color: #d4b8b8;
    }
    .form-group {
        text-align: center;
        margin: 20px auto;
    }
    .form-group1 {
        margin-left: 37%;
    }
   
</style>

<form asp-action="Create"asp-controller="University">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название факультета</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group1">
        <label asp-for="Rating" class="control-label">Рейтинг</label>
         <input type="text" asp-for="Rating" class="form-control" />
     </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default"/>
    </div>

</form>

WebApplication2/Views/University/SortByRating.cshtml
@model IEnumerable<WebApplication2.Models.University>
@{
    ViewBag.Title = "Все факультеты";
}
<a class="new"asp-action="Create">Добаление факультета</a>
<a class="new"asp-action="SortByRating">Сортировка</a>
<style>
    table {
        width: 300px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру окна  */
        background: #786868
    }

    td {
        text-align: center; /* Выравниваем текст по центру ячейки */
    }

    .new {
        background: #786868;
        box-shadow: 0 0 5px rgb(0,0,0);
        cursor: pointer;
        border-radius: 5px;
        color: rgb(255,255,255);
        border: rgb(0,0,0);
        border-color: #008a77;
        text-align: center;
        display: block;
        width: 300px;
        margin: 20px auto;
    }
    .new2 {
        color: #593a3a;
    }
</style>


<table class="table" border="1">
    <tr><td>Название</td><td>Рейтинг</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Rating</td>
            <th><a class="new2" href="/University/DeleteUniversity/@item.UniversityId">Delete</a></th>
            <th><a class="new2" href="/University/UpdateUniversity/@item.UniversityId">Update</a></th>
        </tr>


    }
</table>

WebApplication2/Views/University/University.cshtml
@model IEnumerable<WebApplication2.Models.University>
@{
    ViewBag.Title = "Все факультеты";
}
<a class="new" asp-action="Create">Добаление факультета</a>
<a class="new" asp-action="SortByRating">Сортировка</a>
<style>
    table {
        width: 300px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру окна  */
        background: #786868
    }

    td {
        text-align: center; /* Выравниваем текст по центру ячейки */
    }
    .new {
        background: #786868;
        box-shadow: 0 0 5px rgb(0,0,0);
        cursor: pointer;
        border-radius: 5px;
        color: rgb(255,255,255);
        border: rgb(0,0,0);
        border-color: #008a77;
        text-align: center;
        display: block;
        width: 300px;
        margin: 20px auto;
    }
    .new2 {
        color: #593a3a;
    }

    
</style>
<table class="table" border="1">
    <tr><td>Название</td><td>Рейтинг</td> </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.Name</td>
    <td>@item.Rating</td>
    <th><a class ="new2" href="/University/DeleteUniversity/@item.UniversityId">Delete</a></th>
    <th><a class ="new2" href="/University/UpdateUniversity/@item.UniversityId">Update</a></th>
</tr>


    }
</table>

WebApplication2/Views/University/UpdateUniversity.cshtml
@model WebApplication2.Models.University
@{ 
    ViewBag.Title = "Udate";
}
@{ var item = Model;}
<style>
    .control-label {
        color: #d4b8b8;
    }

    .form-group {
        text-align: center;
        margin: 20px auto;
    }

    .form-group1 {
        margin-left: 37%;
    }
</style>
<form asp-action="UpdateUniversity" asp-controller="University">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название факультета</label>
        <input type="text" asp-for="Name" class="form-control" value="@item.Name" />
    </div>
    <div class="form-group1">
        <label asp-for="Rating" class="control-label">Рейтинг</label>
        <input type="text" asp-for="Rating" class="form-control" value="@item.Rating" />
    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>

</form>