WebApplication2/Models/Directions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Directions
    {
        public int DirectionsId { get; set; } // пердметы
        public string group { get; set; } // название пердмета
        public int nubmer { get; set; } // количество часов в направлении 
        public int? UniversityId { get; set; }

        public Professors University;
        public ICollection<Students> Student { get; set; }
        public Directions()
        {
            Student = new List<Students>();
        }

    }
}

WebApplication2/Controllers/DirectionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Managers.DirectionsManager;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class DirectionsController : Controller
    {
        private readonly IDirectionsManager Manager;
        public DirectionsController(IDirectionsManager manager)
        {
            Manager = manager;
        }
        public async Task<IActionResult> Directions()
        {
            return View(await Manager.GetAll());
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Directions directions)
        {
            await Manager.Add(directions);
            return RedirectToAction(nameof(Directions));
        }
        [HttpGet]
        public async Task<ActionResult> DeleteDirections(int id)
        {
            await Manager.DeleteById(id);
            return RedirectToAction(nameof(Directions));
        }
        [HttpGet]
        public async Task<ViewResult> UpdateDirections(int id)
        {
            return View(await Manager.GetById(id));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateDirections(int id, Directions directions)
        {
            await Manager.UpdateById(id, directions);
            return RedirectToAction(nameof(Directions));
        }
    }
}

WebApplication2/Views/Directions/Create.cshtml
@model WebApplication2.Models.Directions
@{
    ViewBag.Title = "Добавление предметна";
}
<form asp-action="Create" asp-controller="Directions">
    <div class="form-group">
        <label asp-for="group" class="control-label">Название</label>
        <input type="text" asp-for="group" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="nubmer" class="control-label">Количество часов</label>
        <input type="text" asp-for="nubmer" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

WebApplication2/Views/Directions/Directions.cshtml
@model IEnumerable<WebApplication2.Models.Directions>
@{
    ViewBag.Title = "Все факультеты";
}
<a class="new" asp-action="Create">Добаление предмета</a>
<style>
    table {
        width: 300px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру окна  */
        background: #786868
    }

    td {
        text-align: center; /* Выравниваем текст по центру ячейки */
    }

    .new {
        background: #786868;
        box-shadow: 0 0 5px rgb(0,0,0);
        cursor: pointer;
        border-radius: 5px;
        color: rgb(255,255,255);
        border: rgb(0,0,0);
        border-color: #008a77;
        text-align: center;
        display: block;
        width: 300px;
        margin: 20px auto;
    }

    .new2 {
        color: #593a3a;
    }
</style>
<table class="table" border="1">
    <tr><td>Название</td><td>Количество часов</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.group</td>
            <td>@item.nubmer</td>
            <th><a href="/Directions/DeleteDirections/@item.DirectionsId">Delete</a></th>
            <th><a href="/Directions/UpdateDirections/@item.DirectionsId">Update</a></th>
        </tr>


    }
</table>

WebApplication2/Views/Directions/UpdateDirections.cshtml
@model WebApplication2.Models.Directions
@{
    ViewBag.Title = "Update";
}
@{ var item = Model;}
<form asp-action="UpdateDirections" asp-controller="Directions">
    <div class="form-group">
        <label asp-for="group" class="control-label">Название</label>
        <input type="text" asp-for="group" class="form-control" value="@item.group" />
    </div>
    <div class="form-group">
        <label asp-for="nubmer" class="control-label">Часы</label>
        <input type="text" asp-for="nubmer" class="form-control" value="@item.nubmer" />
    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>

</form>