WebApplication2/Models/Groups.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Groups
    {
        public int GroupsId { get; set; }
        public string Name { get; set; }
        public int number{ get; set; }

        public ICollection<Professors> Professor { get; set; }
        public Groups()
        {
            Professor = new List<Professors>();
        }
    }
}

WebApplication2/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Managers.GroupsManager;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroupsManager Manager;
        public GroupsController(IGroupsManager manager)
        {
            Manager = manager;
        }
        public async Task<IActionResult> Groups()
        {
            return View(await Manager.GetAll());
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Groups groups)
        {
            await Manager.Add(groups);
            return RedirectToAction(nameof(Groups));
        }
        [HttpGet]
        public async Task<ActionResult> DeleteGroups(int id)
        {
            await Manager.DeleteById(id);



            return RedirectToAction(nameof(Groups));
        }
        [HttpGet]
        public async Task<ViewResult> UpdateGroups(int id)
        {
            return View(await Manager.GetById(id));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateGroups(int id, Groups groups)
        {
            await Manager.UpdateById(id, groups);
            return RedirectToAction(nameof(Groups));
        }
    }

}

WebApplication2/Views/Groups/Create.cshtml
@model WebApplication2.Models.Groups
@{
    ViewBag.Title = "Добавление пользователи";
}
<form asp-action="Create"asp-controller="Groups">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="number" class="control-label">Количество</label>
         <input type="text" asp-for="number" class="form-control" />
     </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default"/>
    </div>
</form>

WebApplication2/Views/Groups/Groups.cshtml
@model IEnumerable<WebApplication2.Models.Groups>
@{
    ViewBag.Title = "Все факультеты";
}
<a  class="new" asp-action="Create">Добаление группы</a>
<style>
    table {
        width: 300px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру окна  */
        background: #786868
    }

    td {
        text-align: center; /* Выравниваем текст по центру ячейки */
    }

    .new {
        background: #786868;
        box-shadow: 0 0 5px rgb(0,0,0);
        cursor: pointer;
        border-radius: 5px;
        color: rgb(255,255,255);
        border: rgb(0,0,0);
        border-color: #008a77;
        text-align: center;
        display: block;
        width: 300px;
        margin: 20px auto;
    }

    .new2 {
        color: #593a3a;
    }
</style>
<table class="table" border="1">
    <tr><td>Название</td><td>Количество учащихся</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.number</td>
            <th><a href="/Groups/DeleteGroups/@item.GroupsId">Delete</a></th>
            <th><a href="/Groups/UpdateGroups/@item.GroupsId">Update</a></th>
        </tr>


    }
</table>

WebApplication2/Views/Groups/UpdateGroups.cshtml
@model WebApplication2.Models.Groups
@{
    ViewBag.Title = "Udate";
}
@{ var item = Model;}
<form asp-action="UpdateGroups" asp-controller="Groups">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" value="@item.Name" />
    </div>
    <div class="form-group">
        <label asp-for="number" class="control-label">number</label>
        <input type="text" asp-for="number" class="form-control" value="@item.number" />
    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>

</form>