WebApplication2/Models/Sections.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Sections
    {
        public int SectionsId { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public int? UniversityId { get; set; }

 


    }
}

WebApplication2/Controllers/SectionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Managers.SectionsManager;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class SectionsController : Controller
    {
        private readonly ISectionsManager Manager;
        public SectionsController(ISectionsManager manager)
        {
            Manager = manager;
        }
        public async Task<IActionResult> Sections()
        {
            return View(await Manager.GetAll());
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(Sections sections)
        {
            await Manager.Add(sections);
            return RedirectToAction(nameof(Sections));
        }
        [HttpGet]
        public async Task<ActionResult> DeleteSections(int id)
        {
            await Manager.DeleteById(id);
            return RedirectToAction(nameof(Sections));
        }
        [HttpGet]
        public async Task<ViewResult> UpdateSections(int id)
        {
            return View(await Manager.GetById(id));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateSections(int id, Sections sections)
        {
            await Manager.UpdateById(id, sections);
            return RedirectToAction(nameof(Sections));
        }
    }
}

WebApplication2/Views/Sections/Create.cshtml
@model WebApplication2.Models.Sections
@{
    ViewBag.Title = "Добавление секции";
}
<form asp-action="Create"asp-controller="Sections">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Number" class="control-label">Количество человек</label>
         <input type="text" asp-for="Number" class="form-control" />
     </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default"/>
    </div>
</form>

WebApplication2/Views/Sections/Sections.cshtml
@model IEnumerable<WebApplication2.Models.Sections>
@{
    ViewBag.Title = "Все факультеты";
}
<a  class="new" asp-action="Create">Добаление секции</a>
<style>
    table {
        width: 300px; /* Ширина таблицы */
        margin: auto; /* Выравниваем таблицу по центру окна  */
        background: #786868
    }

    td {
        text-align: center; /* Выравниваем текст по центру ячейки */
    }

    .new {
        background: #786868;
        box-shadow: 0 0 5px rgb(0,0,0);
        cursor: pointer;
        border-radius: 5px;
        color: rgb(255,255,255);
        border: rgb(0,0,0);
        border-color: #008a77;
        text-align: center;
        display: block;
        width: 300px;
        margin: 20px auto;
    }

    .new2 {
        color: #593a3a;
    }
</style>
<table class="table" border="1">
    <tr><td>Название</td><td>Количество</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Number</td>
            <th><a href="/Sections/DeleteSections/@item.SectionsId">Delete</a></th>
            <th><a href="/Sections/UpdateSections/@item.SectionsId">Update</a></th>
        </tr>


    }
</table>

WebApplication2/Views/Sections/UpdateSections.cshtml
@model WebApplication2.Models.Sections
@{
    ViewBag.Title = "Update";
}
@{ var item = Model;}
<form asp-action="UpdateSections" asp-controller="Sections">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" value="@item.Name" />
    </div>
    <div class="form-group">
        <label asp-for="Number" class="control-label">number</label>
        <input type="text" asp-for="Number" class="form-control" value="@item.Number" />
    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>

</form>